"""Generate documentation tables from the executable parameter/module schemas."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from gridform_core.parameters import parameter_schema  # noqa: E402


def _cell(value: object) -> str:
    if value is None or value == "":
        return "—"
    if isinstance(value, (dict, list, tuple, bool, int, float)):
        text = json.dumps(value, ensure_ascii=False, sort_keys=True)
    else:
        text = str(value)
    return text.replace("|", "\\|").replace("\n", " ")


def _implementation_source(entry_point: str) -> Path:
    module_name = entry_point.split(":", 1)[0]
    candidate = ROOT / (module_name.replace(".", "/") + ".py")
    if candidate.is_file():
        return candidate
    package = ROOT / module_name.replace(".", "/") / "__init__.py"
    if package.is_file():
        return package
    raise FileNotFoundError(f"Cannot locate implementation source for {entry_point}")


def _portable_source_sha256(path: Path) -> str:
    """Hash Python source independently of the checkout line-ending policy."""
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n").replace("\r", "\n")
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def render_parameters() -> str:
    rows = parameter_schema()["parameters"]
    lines = [
        "# Runtime parameter catalogue",
        "",
        "Generated by `scripts/generate_reference_tables.py`; do not edit by hand.",
        "",
        "| ID | Group | Type | Default | Unit | Category | Visibility | Owner | Experimental |",
        "|---|---|---:|---:|---|---|---|---|---:|",
    ]
    for row in rows:
        lines.append(
            "| " + " | ".join(_cell(row.get(key)) for key in (
                "id", "group", "value_type", "default", "unit", "category",
                "visibility", "module_owner", "experimental",
            )) + " |"
        )
    lines.extend(("", f"Parameter count: **{len(rows)}**.", ""))
    return "\n".join(lines)


def render_modules() -> str:
    manifests = []
    for path in sorted((ROOT / "gridform_core" / "manifests").glob("*.json")):
        row = json.loads(path.read_text(encoding="utf-8"))
        source = _implementation_source(str(row["implementation"]))
        row["source"] = source.relative_to(ROOT).as_posix()
        row["source_sha256"] = _portable_source_sha256(source)
        manifests.append(row)
    lines = [
        "# Shipped module catalogue",
        "",
        "Generated from `gridform_core/manifests/*.json` by "
        "`scripts/generate_reference_tables.py`; do not edit by hand.",
        "",
        "| ID | Slot | Version | Contract | Solver contract | Status | Required selection | Implementation source | Source SHA-256 |",
        "|---|---|---|---|---|---|---:|---|---|",
    ]
    for row in sorted(manifests, key=lambda value: (str(value["slot"]), str(value["id"]))):
        lines.append(
            "| " + " | ".join(_cell(value) for value in (
                row.get("id"), row.get("slot"), row.get("version"),
                row.get("contract_version"),
                row.get("solver_contract", {}).get("defaults", {}).get("contract_version"),
                row.get("status"), row.get("selection_required"), row.get("source"),
                row.get("source_sha256"),
            )) + " |"
        )
    lines.extend(("", f"Shipped manifest count: **{len(manifests)}**.", ""))
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = {
        ROOT / "docs" / "generated" / "PARAMETERS.md": render_parameters(),
        ROOT / "docs" / "generated" / "MODULES.md": render_modules(),
    }
    mismatches = []
    for path, content in outputs.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                mismatches.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"Wrote {path.relative_to(ROOT)}")
    if mismatches:
        raise SystemExit("Generated reference tables are stale: " + ", ".join(mismatches))


if __name__ == "__main__":
    main()
