"""Generate documentation tables from the executable parameter/module schemas."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from gridform_core.parameters import parameter_schema  # noqa: E402


def _cell(value: object) -> str:
    if value is None or value == "":
        return "—"
    if isinstance(value, (dict, list, tuple, bool, int, float)):
        text = json.dumps(value, ensure_ascii=False, sort_keys=True)
    else:
        text = str(value)
    return text.replace("|", "\\|").replace("\n", " ")


def _implementation_source(entry_point: str) -> Path:
    module_name = entry_point.split(":", 1)[0]
    candidate = ROOT / (module_name.replace(".", "/") + ".py")
    if candidate.is_file():
        return candidate
    package = ROOT / module_name.replace(".", "/") / "__init__.py"
    if package.is_file():
        return package
    raise FileNotFoundError(f"Cannot locate implementation source for {entry_point}")


def _portable_source_sha256(path: Path) -> str:
    """Hash Python source independently of the checkout line-ending policy."""
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n").replace("\r", "\n")
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def render_parameters() -> str:
    rows = parameter_schema()["parameters"]
    lines = [
        "# Runtime parameter catalogue",
        "",
        "Generated by `scripts/generate_reference_tables.py`; do not edit by hand.",
        "",
        "| ID | Group | Type | Default | Unit | Category | Visibility | Owner | Experimental |",
        "|---|---|---:|---:|---|---|---|---|---:|",
    ]
    for row in rows:
        lines.append(
            "| " + " | ".join(_cell(row.get(key)) for key in (
                "id", "group", "value_type", "default", "unit", "category",
                "visibility", "module_owner", "experimental",
            )) + " |"
        )
    lines.extend(("", f"Parameter count: **{len(rows)}**.", ""))
    return "\n".join(lines)


def render_modules() -> str:
    manifests = []
    for path in sorted((ROOT / "gridform_core" / "manifests").glob("*.json")):
        row = json.loads(path.read_text(encoding="utf-8"))
        source = _implementation_source(str(row["implementation"]))
        row["source"] = source.relative_to(ROOT).as_posix()
        row["source_sha256"] = _portable_source_sha256(source)
        manifests.append(row)
    lines = [
        "# Shipped module catalogue",
        "",
        "Generated from `gridform_core/manifests/*.json` by "
        "`scripts/generate_reference_tables.py`; do not edit by hand.",
        "",
        "| ID | Slot | Version | Contract | Solver contract | Status | Required selection | Implementation source | Source SHA-256 |",
        "|---|---|---|---|---|---|---:|---|---|",
    ]
    for row in sorted(manifests, key=lambda value: (str(value["slot"]), str(value["id"]))):
        lines.append(
            "| " + " | ".join(_cell(value) for value in (
                row.get("id"), row.get("slot"), row.get("version"),
                row.get("contract_version"),
                row.get("solver_contract", {}).get("defaults", {}).get("contract_version"),
                row.get("status"), row.get("selection_required"), row.get("source"),
                row.get("source_sha256"),
            )) + " |"
        )
    lines.extend(("", f"Shipped manifest count: **{len(manifests)}**.", ""))
    return "\n".join(lines)


def render_methodology_profiles() -> str:
    """docs/generated/METHODOLOGY_PROFILES.md from the methodology catalogue
    (profiles, corrections, declared deviations, generic advisories)."""

    from gridform_core.methodology import CATALOGUE_ROOT, load_catalogue, resolve_methodology

    catalogue = load_catalogue()
    deviations = json.loads((CATALOGUE_ROOT / "declared_deviations.json").read_text(encoding="utf-8"))["deviations"]
    advisories = json.loads((CATALOGUE_ROOT / "advisories.json").read_text(encoding="utf-8"))["advisories"]
    resolved = {profile_id: resolve_methodology(profile_id, catalogue=catalogue) for profile_id in catalogue.profiles}
    lines = [
        "# Methodology profiles",
        "",
        "Generated by `scripts/generate_reference_tables.py` from `gridform_core/data/methodology/`",
        "(the catalogue that runs resolve their methodology from); do not edit by hand.",
        "",
        f"Catalogue sha256: `{catalogue.catalogue_sha256}`.",
        "",
        "A Run records the profile id, version, definition hash and applied-correction hash in",
        "`resolved-run.json`, provenance and status; comparisons treat the profile as part of the method",
        "dimension. Universal corrections apply to every profile; profile-gated corrections apply only",
        "to the profiles that enable them. Rule sets ask `ResolvedMethodology.enabled(<correction id>)`;",
        "they never compare profile ids.",
        "",
        "## Profiles",
        "",
        "| Profile id | Label | Note | Default | Frozen | Version | Gated corrections | Applied corrections | Result publication | External code | Golden family |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for profile in catalogue.profiles.values():
        gated = "all" if profile.gated_corrections == "*" else (", ".join(profile.gated_corrections) or "none")
        lines.append(
            "| " + " | ".join(
                _cell(value) for value in (
                    f"`{profile.id}`", profile.label, profile.note, profile.default, profile.frozen, profile.version,
                    gated, len(resolved[profile.id].applied_correction_ids), profile.result_publication.get("rule"),
                    profile.external_code_policy, profile.golden_family,
                )
            ) + " |"
        )
    for profile in catalogue.profiles.values():
        if not profile.frozen:
            continue
        lines += ["", f"### Frozen profile `{profile.id}`", "", "Reference configuration (written into the Study when the profile is chosen; a deviating value is allowed and recorded on the Run):", ""]
        for section in ("modules", "parameters"):
            for key, value in sorted(profile.reference_configuration.get(section, {}).items()):
                lines.append(f"- {section} `{key}` = `{value}`")
        lines += ["", "Supported modules (module id: accepted scientific versions):", ""]
        if profile.supported_modules == "*":
            lines.append("- any")
        else:
            for module_id, versions in sorted(profile.supported_modules.items()):  # type: ignore[union-attr]
                lines.append(f"- `{module_id}`: " + ", ".join(f"`{version}`" for version in versions))
        lines += ["", f"Supported extensions: {'any' if profile.supported_extensions == '*' else (', '.join(profile.supported_extensions) or 'none')}.", "", "Supported data packs:", ""]
        if profile.supported_data_packs == "*":
            lines.append("- any")
        else:
            for pack in profile.supported_data_packs:  # type: ignore[union-attr]
                pinned = "not pinned" if pack.get("manifest_sha256") == "*" else f"{len(pack.get('manifest_sha256') or [])} pinned manifest sha256"
                lines.append(f"- `{pack['id']}` ({pack.get('label', '')}; {pack['pack_class']}; {pinned})")
    lines += [
        "",
        "## Corrections",
        "",
        "Track `universal` applies to every profile; `profile_gated` only where the profile enables it.",
        "",
        "| Correction id | Track | Applies to | Scope | Affects | Findings | Introduced in | Description |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for correction in sorted(catalogue.corrections.values(), key=lambda item: item.id):
        applies = [profile_id for profile_id, methodology in resolved.items() if correction.id in methodology.applied_correction_ids]
        lines.append(
            "| " + " | ".join(
                _cell(value) for value in (
                    f"`{correction.id}`", correction.track, ", ".join(applies) or "none", correction.scope,
                    ", ".join(correction.affects), ", ".join(correction.findings), correction.introduced_in, correction.description,
                )
            ) + " |"
        )
    lines += [
        "",
        "Corrections recorded only in module version bumps (`docs/release/VERSION_LEDGER.json`) or golden",
        "revisions, and the golden columns each correction changed, are listed in",
        "`docs/release/P0_GOLDEN_DELTA.md`.",
        "",
        "## Declared deviations",
        "",
        "Model behaviour a profile keeps on purpose, with a falsifiable signature tested on the run's own",
        "ledger (`gridform_core/data/methodology/declared_deviations.json`).",
        "",
        "| Deviation | Profiles | Findings | Gate effect | Description |",
        "|---|---|---|---|---|",
    ]
    for row in deviations:
        lines.append(
            "| " + " | ".join(
                _cell(value) for value in (
                    row["id"], ", ".join(row.get("profiles") or []), ", ".join(row.get("findings") or []),
                    row.get("gate_effect"), row.get("description"),
                )
            ) + " |"
        )
    lines += ["", "## Generic read-time advisories", "", "| Advisory | Applies to | Severity | Title |", "|---|---|---|---|"]
    for row in advisories:
        lines.append("| " + " | ".join(_cell(row.get(key)) for key in ("id", "applies_to", "severity", "title")) + " |")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = {
        ROOT / "docs" / "generated" / "PARAMETERS.md": render_parameters(),
        ROOT / "docs" / "generated" / "MODULES.md": render_modules(),
        ROOT / "docs" / "generated" / "METHODOLOGY_PROFILES.md": render_methodology_profiles(),
    }
    mismatches = []
    for path, content in outputs.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                mismatches.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"Wrote {path.relative_to(ROOT)}")
    if mismatches:
        raise SystemExit("Generated reference tables are stale: " + ", ".join(mismatches))


if __name__ == "__main__":
    main()
