"""Editorial content for both languages. No unverified download or DOI URLs."""
from html import escape
import json

def pages(w):
    t, a, url, tag, note, table, cards = (w.t, w.a, w.url, w.tag, w.note, w.table, w.cards)
    result = []

    def add(path, en, zh, intro_en, intro_zh, body, kicker=None):
        title = t(en, zh)
        intro = t(intro_en, intro_zh)
        result.append((path, title, intro, w.heading(kicker or t('VALUE / RESOURCES', 'VALUE / 研究资源'), title, intro) + body))

    def section(title, body, id=''):
        return f'<section class="page-section"' + (f' id="{id}"' if id else '') + f'><h2>{title}</h2>{body}</section>'

    def para(en, zh):
        return '<p>' + t(en, zh) + '</p>'

    def steps(items):
        return '<ol>' + ''.join(('<li>' + x + '</li>' for x in items)) + '</ol>'

    def links(items):
        return '<div class="actions">' + ''.join((a(p, en, zh, 'button button-outline') for p, en, zh in items)) + '</div>'
    add('models', 'VALUE system modelling', 'VALUE 电力系统建模', 'Operation and investment evolution within explicit system boundaries.', '在明确系统边界下研究运行与投资演化。', w.product_cards())
    body = f'<div class="feature-split"><div><h2>{t('Operation informs investment.', '运行结果，反馈投资决策。')}</h2>' + para('VALUE connects operational simulation with investment decisions across years. A study describes the scenario; a run records one execution and its results.', 'VALUE 将运行模拟与跨年度投资决策连接起来。Study 保存研究配置，Run 记录一次具体执行与结果。') + para('The research boundary is explicit: technologies, demand, network representation and investment assumptions belong to a particular study configuration.', '技术对象、需求、网络表示与投资假设都属于具体研究配置，模型边界随配置清晰披露。') + links([('docs/value', 'Read the guide', '阅读使用指南'), ('releases?product=value', 'Release status', '查看发布状态')]) + '</div>' + w.diagram() + '</div>'
    body = body.replace('/releases?product=value/', '/releases/?product=value')
    body += section(t('A cycle across three stages', '三个阶段组成年度循环'), cards([(t('Define the study', '定义研究'), t('Set inputs, scenario assumptions, configuration and module versions before launching a run.', '明确输入、情景假设、研究配置和模块版本，再启动运行。'), ''), (t('Simulate operation', '模拟运行'), t('Represent half-hourly dispatch, storage operation and settlement within the configured network boundary.', '在选定的网络边界内，模拟半小时调度、储能运行与结算。'), ''), (t('Update the system', '更新系统'), t('Use operational outcomes in annual investment decisions, then carry the changed assets into the next year.', '将运行结果用于年度投资决策，再以变化后的资产进入下一年。'), '')]))
    body += section(t('Configurations are part of the method', '配置也是方法的一部分'), table([t('Configuration', '配置'), t('What it represents', '表示什么'), t('Scope and next steps', '适用范围与后续工作')], [(t('National baseline', '全国基线'), t('System-level operation and investment with a national boundary.', '全国边界下的系统运行与投资。'), t('Engineering repeatability applies to the tested configuration; global optimality requires separate analysis.', '工程可重复性适用于已测试配置；全局最优需独立分析。')), (t('GB zonal study', '英国分区研究'), t('A fixed, lossless transport representation: 23 zones, 22 corridors and two boundary constraints.', '固定、无损的分区输电表示：23 个区域、22 条通道与两项边界约束。'), t('This configuration uses a lossless zonal transport model.', '本配置采用分区无损输电模型。'))]))
    body += note(t('Read the evidence with its scope', '连同范围一起阅读验证结果'), t('The 2025–2034 national baseline completed 175,200 half-hour periods and repeated settlement results in engineering checks. These results record this national baseline configuration.', '2025–2034 全国基线完成 175,200 个半小时时段，工程复跑结算结果一致。这些结果记录的是该全国基线配置。'))
    body += links([('studies/national-baseline', 'National baseline', '全国基线案例'), ('validation', 'Validation & limitations', '验证与限制'), ('cite', 'Cite this product', '引用此产品')])
    add('models/value', 'Power systems, evolving.', '电力系统，持续演化。', 'Connect half-hourly operation with annual investment decisions.', '连接半小时运行与年度投资决策。', body, 'VALUE / ' + t('SYSTEM EVOLUTION', '系统演化'))
    study_data = [('value-101', 'value', 'VALUE 101', t('A first day in the model', '理解模型中的一天'), t('One day, 48 half-hour periods and synthetic teaching data.', '一天、48 个半小时时段与合成教学数据。'), t('Teaching data included', '随包教学数据')), ('national-baseline', 'value', t('National baseline', '全国十年基线'), t('Follow a decade of system evolution', '追踪十年的系统演化'), t('2025–2034 operation and annual investment, with scoped engineering repeatability evidence.', '2025–2034 年运行与投资，附有范围明确的工程可重复性证据。'), t('Engineering checks completed', '基线工程检查已完成')), ('gb-zonal', 'value', t('GB zonal study', '英国分区研究'), t('Give the network a boundary', '为网络约束明确边界'), t('23 zones and a fixed transport network. Validation is tracked independently from the national baseline.', '23 个区域与固定输电网络，验证状态独立于全国基线。'), t('Longer-horizon validation planned', '长期情景验证列入后续研究'))]
    body = '<div class="filter-bar" role="group" aria-label="' + t('Filter by product', '按产品筛选') + '">' + ''.join((f'<button class="filter-button" data-study-filter="{v}" aria-pressed="{str(v == 'all').lower()}">{label}</button>' for v, label in [('all', t('All studies', '全部案例')), ('value', 'VALUE')])) + '</div><p class="sr-only" data-filter-status aria-live="polite"></p><div class="study-grid">'
    for slug, prod, title, sub, desc, status in study_data:
        body += f'<article class="content-card" data-study-product="{prod}"><p class="eyebrow">{prod.upper()}</p><h2 style="font-size:1.8rem">{title}</h2><h3>{sub}</h3><p>{desc}</p><div class="meta-row">{tag(status, status)}</div>{a('studies/' + slug, 'Read study', '阅读案例')}</article>'
    body += '</div>' + note(t('Readiness is specific to each study', '案例状态逐项披露'), t('Public materials, engineering checks, scientific review and reproducibility conditions are recorded separately. Scientific interpretation uses the full study assumptions and independent review.', '材料公开、工程检查、科学审阅与复现条件分别记录。科学解释结合完整研究假设与独立审阅。'))
    add('studies', 'Start with a study.', '从一个案例开始。', 'Understand the question, the configuration and the evidence before running the model.', '先了解研究问题、配置与证据，再开始运行模型。', body, t('STUDIES / LEARN BY REPRODUCING', '案例 / 从复现中学习'))

    def study_page(slug, title, zh, intro, zhintro, sections, status):
        body = '<div class="meta-row">' + tag(status[0], status[1]) + tag('Evidence snapshot · 2 October 2026', '证据快照 · 2026年10月2日') + '</div>'
        for h, p in sections:
            body += section(h, p)
        body += links([('releases', 'Software availability', '软件发布状态'), ('data', 'Data & licences', '数据与许可'), ('cite', 'Citation guidance', '引用说明')])
        add('studies/' + slug, title, zh, intro, zhintro, body, t('STUDY / CONFIGURATION & EVIDENCE', '案例 / 配置与证据'))
    study_page('value-101', 'VALUE 101: one day, 48 steps.', 'VALUE 101：一天，48 个时段。', 'A synthetic teaching case for understanding inputs, operations and result interpretation.', '用合成教学案例理解输入、运行与结果解释。', [(t('The research question', '研究问题'), para('How do the model’s inputs and choices flow into half-hourly operation? The teaching case reduces the time scope so you can inspect a full day before attempting a longer study.', '模型输入与选择如何传递到半小时运行？教学案例缩小时间范围，让你在长期研究之前先理解完整的一天。')), (t('Reproduction sequence', '复现顺序'), steps([t('Obtain a matching VALUE software release and its VALUE 101 teaching package.', '获取版本匹配的 VALUE 软件与 VALUE 101 教学包。'), t('Check the package README, data licence, environment and input identity.', '核对包内 README、数据许可、运行环境与输入身份。'), t('Create or open the teaching Study, confirm its 48 periods and explicitly start a Run.', '创建或打开教学 Study，确认 48 个时段，再显式启动 Run。'), t('Inspect the result tables and compare against the reference bundled with that exact release.', '查看结果表，并与该版本随附的参考结果比较。')]) + a('docs/value', 'Read the installation and workflow guide', '阅读环境与工作流程指南')), (t('Materials and limits', '材料与边界'), para('The synthetic teaching data carries CC0. Public download packaging is pending. The case teaches model inputs, operation and result interpretation with synthetic data.', '合成教学数据使用 CC0 许可。公开下载包仍待发布。此案例使用合成数据讲解模型输入、运行与结果解释。'))], ('Teaching case', '教学案例'))
    study_page('national-baseline', 'A decade of system evolution.', '十年的系统演化。', 'VALUE national baseline, 2025–2034.', 'VALUE 全国基线，2025–2034。', [(t('Question and configuration', '研究问题与配置'), para('Explore the interaction between system operation and annual investment over ten years. The baseline’s input and module identities matter: changing either creates a different experiment.', '研究十年间系统运行与年度投资的相互作用。输入与模块身份是基线的一部分，更改其中任何一项都会形成不同实验。')), (t('Engineering evidence', '工程证据'), table([t('Check', '检查'), t('Recorded outcome', '记录结果')], [(t('Time coverage', '时间覆盖'), t('175,200 half-hour periods completed for 2025–2034.', '2025–2034 年共 175,200 个半小时时段已完成。')), (t('Repeatability', '可重复性'), t('A rerun reproduced the baseline settlement results.', '基线复跑的结算结果一致。')), (t('Interpretation', '解释范围'), t('Repeatable execution under the tested configuration.', '在已测试配置下的执行可重复性。'))])), (t('Use the evidence correctly', '正确使用验证证据'), para('These checks establish repeatable execution under the specified conditions. Global optimality, prediction and policy interpretation require separate evidence. Scientific interpretation requires the underlying assumptions, data and independent review. Public reproduction also depends on software and data availability.', '上述检查支持指定条件下的可重复执行；全局最优、预测与政策解释需分别补充证据。科学解释仍需结合假设、数据与独立审阅；公开复现还取决于软件与数据是否可获得。') + a('validation', 'Read the validation record', '查看验证记录'))], ('Baseline engineering checks completed', '基线工程检查已完成'))
    study_page('gb-zonal', 'Represent a constrained network.', '表示一个受限的网络。', 'A GB zonal research configuration for VALUE.', 'VALUE 的英国分区研究配置。', [(t('Network representation', '网络表示'), para('This case uses 23 zones, 22 corridors and two boundary constraints, with a fixed, lossless zonal transport formulation. Treat that representation as part of the study’s assumptions.', '本案例使用 23 个区域、22 条通道与两项边界约束，采用固定、无损的分区输电表示。这一网络表示本身就是研究假设的一部分。')), (t('Evidence status', '证据状态'), para('Longer-horizon scenario validation is planned for further research.', '长期情景验证列入后续研究。')), (t('Interpretation boundary', '解释边界'), para('The case uses a lossless zonal transport model. Results should be reported with network assumptions, capacities, scenario identity and validation evidence.', '此案例采用无损分区输电模型。结果须附带网络假设、通道容量、情景身份与验证证据。'))], ('Longer-horizon validation planned', '长期情景验证列入后续研究'))
    selector = f'<div class="release-controls"><label class="field">{t('Product', '产品')}<select aria-label="{t('Product', '产品')}" data-product-select><option value="value">VALUE</option></select></label><label class="field">{t('Version', '版本')}<select disabled aria-label="{t('No public release yet', '尚无公开版本')}"><option>{t('Public release pending', '公开版本待发布')}</option></select></label><label class="field">{t('Platform', '平台')}<select aria-label="{t('Platform', '平台')}" data-platform-select><option value="linux">Linux x86_64</option><option value="windows">Windows x64</option><option value="macos-x64">macOS Intel</option><option value="macos-arm64">macOS Apple Silicon</option></select></label></div>'
    body = '<p>' + a('release-check', 'Installation guide and package status', '安装指南与软件包状态', 'button') + '</p><div class="release-panel">' + selector
    for prod in w.CONFIG['products']:
        single = False
        body += f'<div data-product-panel="{prod['id']}"' + (' hidden' if single else '') + '><div class="status-panel">' + tag('Public release pending', '公开版本待发布') + f'<h2 style="font-size:1.8rem;margin:16px 0">{prod['name']}</h2>'
        body += para('No verified public release files are available yet. Published versions will appear here with a fixed download link, file name, size and matching documentation.', '尚无经核验的公开版本文件。发布后，此处将显示固定下载地址、文件名、大小与匹配文档。')
        body += f'<p data-platform-note="linux">{t('Linux: Full 2026-10-03-rc1 includes private Python and Node; offline installation and scoped four-role tasks passed.', 'Linux：Full 2026-10-03-rc1 内置 Python、Node，断网安装及指定四角色短任务通过。')}</p><p data-platform-note="windows" hidden>{t('Windows 10+ x64: Full 2026-10-03-rc1 includes its runtime and install-value.cmd; native validation and signing are pending.', 'Windows 10+ x64：Full 2026-10-03-rc1 自带环境，使用 install-value.cmd；实机验收及签名待完成。')}</p><p data-platform-note="macos-x64" hidden>{t('macOS 15+ Intel: Full 2026-10-03-rc1 includes its own runtime. Native acceptance, signing and notarisation are pending.', 'macOS 15+ Intel：Full 2026-10-03-rc1 自带环境；实机验收、签名与公证待完成。')}</p><p data-platform-note="macos-arm64" hidden>{t('macOS 15+ Apple Silicon: a separate arm64 Full 2026-10-03-rc1 archive includes its own runtime. Native acceptance, signing and notarisation are pending.', 'macOS 15+ Apple Silicon：提供独立 arm64 Full 2026-10-03-rc1 包及环境；实机验收、签名与公证待完成。')}</p>'
        body += '</div><div class="release-links">' + a('docs/' + prod['id'], 'Read product guide', '阅读产品指南') + a('validation', 'Validation record', '验证记录') + a('cite', 'Citation information', '引用信息') + '</div>'
        for release in prod['releases']:
            body += f'<article class="content-card published-release" data-release-platform="{escape(release['platform'])}"><h3>{escape(release['version'])}</h3><p>{escape(release['date'])} · {escape(release['size'])}</p><p>{escape(release['requirements'])}</p><a class="button" href="{escape(release['url'])}">{t('Download from GitHub', '从 GitHub 下载')}</a></article>'
        body += '</div>'
    body += '</div>'
    body += section(t('Download only what you need', '按需获取材料'), cards([(t('Software & smallest example', '软件与最小示例'), t('Start with the product package and a short example for the same version.', '先获取同一版本的产品软件包与短示例。'), a('docs', 'Read the guides', '阅读指南')), (t('Study data', '研究数据'), t('Follow each dataset’s licence and version. Large research data is distributed independently.', '按每个数据集的许可与版本获取。大型研究数据独立分发。'), a('data', 'Explore data access', '查看数据获取方式')), (t('Record the version', '记录研究版本'), t('Keep the software, configuration, data identities and any verified citation with your study.', '随研究保存软件、配置、数据身份及经核实的引用条目。'), a('cite', 'Prepare a citation', '准备引用'))]))
    body += note(t('Direct distribution', '直接分发'), t('value.ac is the installation entry point. Installers and redistributable large data packages are hosted in the Value repository’s GitHub Releases. Downloads go directly to the selected version; model computation and results stay on your computer.', 'value.ac 是安装入口；完整安装包和获准分发的大数据包托管在 Value 仓库的 GitHub Releases。下载直达所选版本，模型计算和结果保留在用户本机。'))
    add('releases', 'Install VALUE on your computer.', '在电脑上安装 VALUE。', 'Choose your product and platform here, download the package and run its installer locally.', '在这里选择产品和平台，下载完整包，再在本机运行安装器。', body, t('DOWNLOADS / RELEASES', '下载 / 软件版本'))
    body = table([t('Material', '材料'), t('Access and licence', '获取与许可'), t('Distribution', '分发方式')], [('VALUE 101', t('Three synthetic teaching and contract packs are public under CC0 in the Value repository.', '三个 CC0 合成教学与契约数据包已在 Value 仓库公开。'), t('Small example with the matching software release.', '随匹配软件版本提供小型示例。')), (t('Full study data', '完整研究数据'), t('Licence and source depend on the dataset. UK data may require separate permission.', '按具体数据集确认许可与来源。UK 数据可能需要独立授权。'), t('Authorised source; preprocessing and input identity recorded per study.', '授权来源；每项研究记录预处理过程与输入身份。')), (t('Large public datasets', '大型公开数据'), t('Archive and data version must be verified before listing.', '列出前核验归档与数据版本。'), t('Versioned GitHub Releases in hanzohanzhe/Value; select them through value.ac.', '托管在 hanzohanzhe/Value 的版本化 GitHub Releases，通过 value.ac 选择下载。')), (t('Your research outputs', '用户研究结果'), t('Stored and managed by the researcher.', '由研究者保存和管理。'), t('Your local or research compute storage, not the website.', '本地或研究计算存储，不进入官网。'))])
    body += section(t('What every dataset needs', '每个数据集都需要'), cards([(t('Identity', '身份'), t('Source, version, time coverage, units and the study that uses it.', '来源、版本、时间覆盖、单位与使用它的研究。'), ''), (t('Permission', '许可'), t('A data licence and redistribution conditions, independently of the software licence.', '独立于软件许可的数据许可与再分发条件。'), ''), (t('Integrity', '完整性'), t('File name and size for downloadable archives, with a fixed version link.', '可下载归档的文件名、体积与固定版本链接。'), '')]))
    body += note(t('Data source terms', '数据来源条款'), t('Third-party data uses its own redistribution terms. Obtain restricted datasets from their authorised source.', '第三方数据使用其自身再分发条款；受限数据从授权来源获取。'))
    body += '<p>' + w.external('https://github.com/hanzohanzhe/Value/tree/main/data-packs', t('Browse the three published synthetic data packs', '查看三个已公开的合成数据包')) + '</p>'
    add('data', 'Data, with its provenance.', '让数据带着来源。', 'Obtain the smallest relevant dataset, with its own licence and exact version.', '获取所需的最小数据集，并保留其独立许可与准确版本。', body, t('RESOURCES / DATA', '资源 / 数据'))
    body = table([t('Product / configuration', '产品 / 配置'), t('Engineering evidence', '工程证据'), t('Limit of the claim', '结论边界')], [(t('VALUE national baseline', 'VALUE 全国基线'), t('2025–2034 completed; 175,200 half-hours; rerun settlement results matched.', '2025–2034 已完成；175,200 个半小时；复跑结算结果一致。'), t('Applies to repeated execution of the tested baseline; scientific and policy interpretation requires separate review.', '适用于已测试基线的重复执行；科学与政策解释需独立审阅。')), (t('VALUE four user paths', 'VALUE 四条用户路径'), t('Four specified tasks passed after fixes on 2 October 2026. Reproduction, data adaptation and module modification: 48 periods each. Observer extension: 2 periods.', '2026年10月2日，四项指定任务修复后通过。复现、换数据、改模块各 48 时段；observer 扩展为 2 时段。'), t('Short-scope usability and interface checks; full-year scientific validation remains to be completed.', '短范围可用性与接口检查；全年科学验证待完成。')), (t('VALUE GB zonal study', 'VALUE 英国分区研究'), t('Longer-horizon scenario validation is planned for further research.', '依据记录快照，较长时间范围验证仍在进行。'), t('Uses a fixed lossless transport representation with its own validation record.', '采用固定无损输电表示，验证按本配置记录。'))])
    body += note(t('Evidence snapshot · 2 October 2026', '证据快照 · 2026年10月2日'), t('This page records the research status on the stated date. Later releases may supersede it. Engineering completion, scientific review and public availability are tracked separately.', '本页记录所示日期的研究状态。后续版本可能更新此记录。工程完成、科学审阅与公开可获得性分别记录。'))
    body += section(t('Four questions for every study', '每项研究都回答四个问题'), cards([(t('What was tested?', '测试了什么？'), t('Identify the product, configuration, software version and test horizon.', '明确产品、配置、软件版本与测试时间范围。'), ''), (t('What can be reproduced?', '什么可以复现？'), t('Check access to software, inputs, reference outputs and an appropriate environment.', '核对软件、输入、参考输出与运行环境是否可获得。'), ''), (t('What has been reviewed?', '哪些结论经过审阅？'), t('State whether the scientific interpretation has independent review. Assess it using the study assumptions and independent evidence.', '科学结论结合独立审阅与完整研究假设。'), ''), (t('What is public?', '哪些材料已经公开？'), t('List the available code, input data, reference results and their access conditions.', '列出已公开的代码、输入数据、参考结果与获取条件。'), '')], 'path-grid'))
    body += links([('studies', 'Study records', '案例记录'), ('releases', 'Release availability', '发布状态')])
    add('validation', 'Know what the evidence supports.', '了解证据能够支持什么。', 'Engineering evidence is recorded for each product, configuration and version.', '验证对应具体产品、配置与版本，每项结论都需要明确范围。', body, t('RESEARCH / VALIDATION & LIMITS', '研究 / 验证与限制'))
    add('cite', 'Cite VALUE', '引用 VALUE', 'Record the software, configuration and data used.', '记录使用的软件、配置与数据。', '', t('PROJECT / CITATION', '项目 / 引用'))
    archive = w.external('https://github.com/hanzohanzhe/SCHEME-C-PhD-Reproduction', t('Open historical research archive on GitHub', '在 GitHub 查看历史研究档案'))
    body = section(t('The name', '名称的含义'), para('VALUE stands for Variable renewable electricity Allocation, Load-enabled excess-generation Utilisation, and system Evolution. The website presents power-system operation and investment evolution.', 'VALUE 全称为 Variable renewable electricity Allocation, Load-enabled excess-generation Utilisation, and system Evolution。官网介绍电力系统运行与投资演化。'))
    body += section(t('Source availability', '源码获取状态'), para('The source-review snapshot is public in hanzohanzhe/Value, with synthetic teaching data and website source. Use value.ac for installation guidance; complete installer downloads remain pending.', '源码审阅快照已在 hanzohanzhe/Value 公开，包含合成教学数据和网站源码。用户从 value.ac 查看安装指引，完整安装包下载仍待发布。') + w.external('https://github.com/hanzohanzhe/Value', t('VALUE source and data on GitHub', 'GitHub 上的 VALUE 源码与数据')) + note(t('Historical archive', '历史研究档案'), t('The SCHEME-C PhD reproduction repository preserves earlier research. Its numerical reproduction has separate UK data conditions.', 'SCHEME-C 博士复现仓库保存较早的研究档案。其数值复现涉及独立的 UK 数据条件。') + '<br>' + archive))
    body += note(t('Software licence', '软件许可'), t('VALUE software uses Apache-2.0, including commercial use under its terms. Documentation uses CC BY 4.0; VALUE 101 synthetic data uses CC0; third-party dependencies and datasets retain their own terms. Research citation is recommended; software use follows Apache-2.0.', 'VALUE 软件均采用 Apache-2.0，可依其条款用于商业用途。文档采用 CC BY 4.0，VALUE 101 合成数据采用 CC0；第三方依赖与数据保留各自条款。建议在研究成果中引用项目；软件使用遵循 Apache-2.0。'))
    body += section(t('Distribution and permanent references', '分发与持久引用'), para('The website is lightweight. Public source and software releases will be distributed through GitHub; independent archives can preserve public research data and versioned software records. Links are added only after the actual files, licence and citation metadata are checked.', '官网保持轻量。公开源码与软件版本将通过 GitHub 分发；独立归档可保存公开研究数据和有版本的软件记录。只有实际文件、许可与引用元数据核验后才会接入链接。') + '<p>' + w.external('https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases', t('GitHub Releases documentation', 'GitHub Releases 官方说明')) + ' · ' + w.external('https://help.zenodo.org/docs/github/archive-software/github-upload/', t('Zenodo software archiving', 'Zenodo 软件归档')) + '</p>')
    add('about', 'Research with explicit assumptions.', '让研究假设清晰可见。', 'Models, materials and evidence that stay connected.', '让模型、材料与证据保持关联。', body, t('PROJECT / ABOUT VALUE', '项目 / 关于 VALUE'))
    updated = []
    for path, title, desc, body in result:
        if path in {'models/value', 'docs', 'docs/value', 'data', 'validation', 'studies/national-baseline', 'studies/gb-zonal', 'studies/site-design', 'cite'}:
            note_body = t('Read the audited equations, numerical parameters, pseudocode and initial dataset identities. The complete methodology distinguishes implementation, tested examples and remaining reproducibility gaps.', '查看已对照源码的公式、数值参数、伪代码与初始数据身份。完整方法学区分实际实现、已验证小例与尚未补齐的复现条件。')
            if path == 'studies/gb-zonal':
                note_body += t(' The 23-zone configuration below is distinct from the new 11-zone, 14-corridor fixed-fleet package; both are documented separately.', ' 下述23区配置与新增11区、14计算走廊的固定资产研究包不同；方法学分别说明两者。')
            body += section(t('Versioned methodology', '有版本的方法学'), '<p>' + note_body + '</p>' + a('methodology', 'Read the full methodology', '阅读完整方法学'))
        updated.append((path, title, desc, body))
    return updated
